name: ROS2 CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add ROS GPG key manually
      run: |
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

    - name: Set up ROS2 Humble
      uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: humble

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-colcon-common-extensions

    - name: Build workspace
      run: |
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

    - name: Run tests
      run: |
        colcon test
        colcon test-result --verbose

    - name: Lint Python code
      run: |
        if [ -d src ]; then
          flake8 src
        else
          echo "No src directory found, skipping linting."
        fi
